FBZ-10435 add check for env.custom in Puma_legacy
engineyard/ey-cookbooks-dev-v7 pull request #102
Opened 2022-08-08 11:11 UTC by rupikakapoor

2022-09-01 08:16 UTC, kdotbautista approved these changes
LGTM

2022-09-01 21:00 UTC, mushyy requested changes
Missing `source /data/<%= @app_name %>/shared/config/env` Which we should always be written.

2022-09-02 05:30 UTC, rupikakapoor commented
`source /data/<%= @app_name %>/shared/config/env` added to app control script and updated branch

2022-09-02 19:57 UTC, mushyy approved these changes
LGTM

2022-09-02 19:58 UTC, merged