Migrated recipe to be executed on v7
engineyard/ey-cookbooks-dev-v7 pull request #76
Opened 2022-06-11 18:25 UTC by rupikakapoor

2022-06-11 18:30 UTC, mushyy requested changes
Needs to be ran through linting process as per our [CONTRIBUTING.md](https://github.com/engineyard/ey-cookbooks-dev-v7/blob/master/CONTRIBUTING.md) guidelines

2022-06-14 11:42 UTC, rupikakapoor commented
@mushyy: indentation fix is implemented:

```
rupika@Rupikas-iMac ey-cookbooks-dev-v7 % cookstyle               
Inspecting 190 files
..............................................................................................................................................................................................

190 files inspected, no offenses detected
```

2022-06-14 13:07 UTC, mushyy requested changes
Other than the requested change this looks good to me

2022-06-14 13:07 UTC, mushyy commented on cookbooks/ey-nodejs/attributes/default.rb
> +                          when "nodejs_15"
Wrong key for NodeJS should be nodejs_16

2022-06-14 13:13 UTC, rupikakapoor commented
@mushyy fixed

2022-06-14 13:53 UTC, mushyy commented
Looks good to me ready for QA.

2022-06-14 13:53 UTC, merged